### ISSUE TITLE
JPEG datastream contains no image

### ISSUE THREAD

**Issue by karlkoch23** [willglynn/ruby-zbar#2]
zbar is bulid with ImageMagick but method _from_jpeg_ fails with "JPEG datastream contains no image". The standalone application _zbarimg_ processes jpeg images without problems. The gem works with PGM images.

**Comment by anaumov** [comment]
updated link to the post "Build Ubuntu/Debian packages from source (and apply a patch)" http://pascal.bach.ch/2010/05/06/build-ubuntudebian-packages-from-source-and-apply-a-patch/

**Comment by anaumov** [comment]
inspired by @sberryman MiniMagick solution
```ruby
  image = MiniMagick::Image.open(path)
  image.format('pgm')
  ZBar::Image.from_pgm(image.to_blob).process
```
