### ISSUE TITLE
Decoding PNG images

### ISSUE THREAD

**Issue by lanceschi** [willglynn/ruby-zbar#7]
Hi,

I was just trying in IRB your nice binding albeit I wasn't able to decode and process PNG images. I took a look at the source code and  I cound't find any references to PNG file format. I'm a correct? Are there any workarounds, since command line 'zbarimg' can handle those?

Thanks,
Luca

**Comment by andyweiss1982** [comment]
Hi @willglynn, was wondering if you had any insight into an issue I'm having.  I am using the Grim gem to strip a multi-page PDF into one PNG per page.  Then I am trying to read a barcode on each page using the process outlined above.  I am getting an error I've never seen before and did a little source diving into the gem code but can't figure out where max_value is being set.  I am attaching here a screenshot of the error I am getting as well as the PNG file I am trying to read.   Thanks! 

Error:
![screen shot 2015-10-16 at 12 55 08 pm](https://cloud.githubusercontent.com/assets/8116130/10548252/4fbbc9fa-7407-11e5-81d9-9410215dfe5a.png)

PNG I am trying to read:
![pdf_page_1](https://cloud.githubusercontent.com/assets/8116130/10548257/5430a0aa-7407-11e5-9c14-bf3d038c25dc.png)

Source code: Where does $4 come from?
![screen shot 2015-10-16 at 12 58 18 pm](https://cloud.githubusercontent.com/assets/8116130/10548291/8650e694-7407-11e5-88cd-144b6a21107a.png)

**Comment by willglynn** [comment]
`$4` is the fourth capture from that regex, `P5` being the first. 255 is expected, since that corresponds to an 8-bit PGM, which encodes image data identically to zbar's `Y800` format. What is the value in your blob?

**Comment by andyweiss1982** [comment]
@willglynn I got 65535.  Does that seem crazy?

**Comment by andyweiss1982** [comment]
![screen shot 2015-10-16 at 2 40 53 pm](https://cloud.githubusercontent.com/assets/8116130/10550259/f30f6bd2-7413-11e5-9f78-4689c582ea3e.png)
![screen shot 2015-10-16 at 2 41 30 pm](https://cloud.githubusercontent.com/assets/8116130/10550271/05810d52-7414-11e5-87f9-00585d6c278a.png)

**Comment by willglynn** [comment]
That's a 16-bit image, which zbar doesn't support. Convert it to 8-bit before turning into a PGM.

**Comment by andyweiss1982** [comment]
This worked -- thanks @willglynn !
